invitados = ['Angel', 'Jero', 'Miguel']
print(invitados[0], "te invito a cenar")
print(invitados[1], "te invito a cenar")
print(invitados[2], "te invito a cenar")
print(invitados[2], "no puede venir a la cena")
invitados.pop(2)
invitados.append('Paulo')
print(invitados[0], "te invito a cenar")
print(invitados[1], "te invito a cenar")
print(invitados[2], "te invito a cenar")
invitados.append('Maria')
print(invitados)
invitados.insert(4, 'Isa')
print(invitados)
print(invitados[0], "te invito a cenar")
print(invitados[1], "te invito a cenar")
print(invitados[2], "te invito a cenar")
print(invitados[3], "te invito a cenar")
print(invitados[4], "te invito a cenar")
print("Solo hay reservas para dos en el restaurante")
invitados.pop(0)
print(invitados)
invitados.pop(1)
print(invitados)
invitados.pop(0)
print(invitados)
print(invitados[0], "te invito a cenar")
print(invitados[1], "te invito a cenar")
 
print('Tenemos', len(invitados), "para la cena")
